nodeLinker: node-modules

supportedArchitectures:
  os:
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'current'
    - 'x64'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.6.1.cjs
