compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - arm64
    - x64
  libc:
    - msvc
    - glibc
  os:
    - darwin
    - linux
    - win32
