nodeLinker: node-modules

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - arm64
    - x64
  libc:
    - msvc
    - glibc

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
