module.exports = {
  assign: require('lodash.assign'),
  clone: require('lodash.clone'),
  defaults: require('lodash.defaults'),
  extend: require('lodash.assignin'),
  filter: require('lodash.filter'),
  find: require('lodash.find'),
  flatten: require('lodash.flatten'),
  isArray: require('lodash.isarray'),
  isBoolean: require('lodash.isboolean'),
  isFunction: require('lodash.isfunction'),
  isNumber: require('lodash.isnumber'),
  isPlainObject: require('lodash.isplainobject'),
  isString: require('lodash.isstring'),
  last: require('lodash.last'),
  map: require('lodash.map'),
  omit: require('lodash.omit'),
  set: require('lodash.set'),
  uniq: require('lodash.uniq')
};
